title: Container
tagline: "Fast and intuitive dependency injection container."
description: "Container is a small but powerful dependency injection container that allows you to decouple components in your application in order to write clean and testable code."
google_analytics_tracking_id: UA-58477653-1
